version: '3.0'
services:
        db:
                image: mysql:5.6
                volumes:
                 - vol1:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: somewordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress

        web1:
                depends_on:
                        - db
                image: wordpress:latest
                ports: 
                 - "8000:80"
                restart: always
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_NAME: wordpress
volumes: 
       vol1: {} 
